/* tslint:disable */
/* eslint-disable */
/**
 * Social App API
 * Endpoints for user registration, authentication, friend management, and location updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthCheckResponse
 */
export interface AuthCheckResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthCheckResponse
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface FriendRequest
 */
export interface FriendRequest {
    /**
     * 
     * @type {string}
     * @memberof FriendRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FriendRequest
     */
    'friendName': string;
}
/**
 * 
 * @export
 * @interface FriendRequestCreate
 */
export interface FriendRequestCreate {
    /**
     * 
     * @type {string}
     * @memberof FriendRequestCreate
     */
    'friendUsername': string;
}
/**
 * 
 * @export
 * @interface FriendRequests
 */
export interface FriendRequests {
    /**
     * 
     * @type {Array<FriendRequest>}
     * @memberof FriendRequests
     */
    'requestsToYou': Array<FriendRequest>;
    /**
     * 
     * @type {Array<FriendRequest>}
     * @memberof FriendRequests
     */
    'requestsFromYou': Array<FriendRequest>;
}
/**
 * 
 * @export
 * @interface GenericSuccess
 */
export interface GenericSuccess {
    /**
     * 
     * @type {boolean}
     * @memberof GenericSuccess
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GenericSuccess
     */
    'detail'?: string;
}
/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    'latitude': number;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    'longitude': number;
}
/**
 * 
 * @export
 * @interface LocationUser
 */
export interface LocationUser {
    /**
     * 
     * @type {string}
     * @memberof LocationUser
     */
    'username': string;
    /**
     * 
     * @type {Location}
     * @memberof LocationUser
     */
    'location': Location;
    /**
     * 
     * @type {string}
     * @memberof LocationUser
     */
    'ts': string;
}
/**
 * 
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof LoginRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'detail'?: string;
}
/**
 * 
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface SignupResponse
 */
export interface SignupResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SignupResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SignupResponse
     */
    'detail'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check if the user is authenticated and receive user info in that case
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authCheckGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/authCheck`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Send a friend request
         * @param {FriendRequestCreate} friendRequestCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestCreatePost: async (friendRequestCreate: FriendRequestCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'friendRequestCreate' is not null or undefined
            assertParamExists('friendRequestCreatePost', 'friendRequestCreate', friendRequestCreate)
            const localVarPath = `/friend-request/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(friendRequestCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Accept a pending friend request
         * @param {string} id Friend request identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestIdAcceptPost: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('friendRequestIdAcceptPost', 'id', id)
            const localVarPath = `/friend-request/{id}/accept`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cancel a pending friend request
         * @param {string} id Friend request identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestIdCancelPost: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('friendRequestIdCancelPost', 'id', id)
            const localVarPath = `/friend-request/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reject a pending friend request
         * @param {string} id Friend request identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestIdRejectPost: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('friendRequestIdRejectPost', 'id', id)
            const localVarPath = `/friend-request/{id}/reject`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get frend requests for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/friend-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a friend connection
         * @param {string} friendUsername Username of the friend to remove
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendsFriendUsernameDelete: async (friendUsername: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'friendUsername' is not null or undefined
            assertParamExists('friendsFriendUsernameDelete', 'friendUsername', friendUsername)
            const localVarPath = `/friends/{friend_username}`
                .replace(`{${"friend_username"}}`, encodeURIComponent(String(friendUsername)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List usernames of confirmed friends
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/friends`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Report current position and retrieve recent friend locations
         * @param {Location} location 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPost: async (location: Location, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'location' is not null or undefined
            assertParamExists('locationPost', 'location', location)
            const localVarPath = `/location`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(location, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Authenticate a user and receive a session cookie
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginPost: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('loginPost', 'loginRequest', loginRequest)
            const localVarPath = `/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new user account
         * @param {SignupRequest} signupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupPost: async (signupRequest: SignupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signupRequest' is not null or undefined
            assertParamExists('signupPost', 'signupRequest', signupRequest)
            const localVarPath = `/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Check if the user is authenticated and receive user info in that case
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authCheckGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthCheckResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authCheckGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authCheckGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Send a friend request
         * @param {FriendRequestCreate} friendRequestCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async friendRequestCreatePost(friendRequestCreate: FriendRequestCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericSuccess>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.friendRequestCreatePost(friendRequestCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.friendRequestCreatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Accept a pending friend request
         * @param {string} id Friend request identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async friendRequestIdAcceptPost(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericSuccess>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.friendRequestIdAcceptPost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.friendRequestIdAcceptPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cancel a pending friend request
         * @param {string} id Friend request identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async friendRequestIdCancelPost(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericSuccess>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.friendRequestIdCancelPost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.friendRequestIdCancelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Reject a pending friend request
         * @param {string} id Friend request identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async friendRequestIdRejectPost(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericSuccess>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.friendRequestIdRejectPost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.friendRequestIdRejectPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get frend requests for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async friendRequestsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FriendRequests>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.friendRequestsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.friendRequestsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a friend connection
         * @param {string} friendUsername Username of the friend to remove
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async friendsFriendUsernameDelete(friendUsername: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericSuccess>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.friendsFriendUsernameDelete(friendUsername, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.friendsFriendUsernameDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List usernames of confirmed friends
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async friendsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.friendsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.friendsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Report current position and retrieve recent friend locations
         * @param {Location} location 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async locationPost(location: Location, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LocationUser>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.locationPost(location, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.locationPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Authenticate a user and receive a session cookie
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginPost(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginPost(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.loginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericSuccess>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.logoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new user account
         * @param {SignupRequest} signupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signupPost(signupRequest: SignupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signupPost(signupRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.signupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Check if the user is authenticated and receive user info in that case
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authCheckGet(options?: RawAxiosRequestConfig): AxiosPromise<AuthCheckResponse> {
            return localVarFp.authCheckGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Send a friend request
         * @param {DefaultApiFriendRequestCreatePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestCreatePost(requestParameters: DefaultApiFriendRequestCreatePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericSuccess> {
            return localVarFp.friendRequestCreatePost(requestParameters.friendRequestCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Accept a pending friend request
         * @param {DefaultApiFriendRequestIdAcceptPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestIdAcceptPost(requestParameters: DefaultApiFriendRequestIdAcceptPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericSuccess> {
            return localVarFp.friendRequestIdAcceptPost(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cancel a pending friend request
         * @param {DefaultApiFriendRequestIdCancelPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestIdCancelPost(requestParameters: DefaultApiFriendRequestIdCancelPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericSuccess> {
            return localVarFp.friendRequestIdCancelPost(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reject a pending friend request
         * @param {DefaultApiFriendRequestIdRejectPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestIdRejectPost(requestParameters: DefaultApiFriendRequestIdRejectPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericSuccess> {
            return localVarFp.friendRequestIdRejectPost(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get frend requests for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendRequestsGet(options?: RawAxiosRequestConfig): AxiosPromise<FriendRequests> {
            return localVarFp.friendRequestsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a friend connection
         * @param {DefaultApiFriendsFriendUsernameDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendsFriendUsernameDelete(requestParameters: DefaultApiFriendsFriendUsernameDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericSuccess> {
            return localVarFp.friendsFriendUsernameDelete(requestParameters.friendUsername, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List usernames of confirmed friends
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        friendsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.friendsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Report current position and retrieve recent friend locations
         * @param {DefaultApiLocationPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPost(requestParameters: DefaultApiLocationPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<LocationUser>> {
            return localVarFp.locationPost(requestParameters.location, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Authenticate a user and receive a session cookie
         * @param {DefaultApiLoginPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginPost(requestParameters: DefaultApiLoginPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.loginPost(requestParameters.loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutPost(options?: RawAxiosRequestConfig): AxiosPromise<GenericSuccess> {
            return localVarFp.logoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new user account
         * @param {DefaultApiSignupPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupPost(requestParameters: DefaultApiSignupPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignupResponse> {
            return localVarFp.signupPost(requestParameters.signupRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for friendRequestCreatePost operation in DefaultApi.
 * @export
 * @interface DefaultApiFriendRequestCreatePostRequest
 */
export interface DefaultApiFriendRequestCreatePostRequest {
    /**
     * 
     * @type {FriendRequestCreate}
     * @memberof DefaultApiFriendRequestCreatePost
     */
    readonly friendRequestCreate: FriendRequestCreate
}

/**
 * Request parameters for friendRequestIdAcceptPost operation in DefaultApi.
 * @export
 * @interface DefaultApiFriendRequestIdAcceptPostRequest
 */
export interface DefaultApiFriendRequestIdAcceptPostRequest {
    /**
     * Friend request identifier
     * @type {string}
     * @memberof DefaultApiFriendRequestIdAcceptPost
     */
    readonly id: string
}

/**
 * Request parameters for friendRequestIdCancelPost operation in DefaultApi.
 * @export
 * @interface DefaultApiFriendRequestIdCancelPostRequest
 */
export interface DefaultApiFriendRequestIdCancelPostRequest {
    /**
     * Friend request identifier
     * @type {string}
     * @memberof DefaultApiFriendRequestIdCancelPost
     */
    readonly id: string
}

/**
 * Request parameters for friendRequestIdRejectPost operation in DefaultApi.
 * @export
 * @interface DefaultApiFriendRequestIdRejectPostRequest
 */
export interface DefaultApiFriendRequestIdRejectPostRequest {
    /**
     * Friend request identifier
     * @type {string}
     * @memberof DefaultApiFriendRequestIdRejectPost
     */
    readonly id: string
}

/**
 * Request parameters for friendsFriendUsernameDelete operation in DefaultApi.
 * @export
 * @interface DefaultApiFriendsFriendUsernameDeleteRequest
 */
export interface DefaultApiFriendsFriendUsernameDeleteRequest {
    /**
     * Username of the friend to remove
     * @type {string}
     * @memberof DefaultApiFriendsFriendUsernameDelete
     */
    readonly friendUsername: string
}

/**
 * Request parameters for locationPost operation in DefaultApi.
 * @export
 * @interface DefaultApiLocationPostRequest
 */
export interface DefaultApiLocationPostRequest {
    /**
     * 
     * @type {Location}
     * @memberof DefaultApiLocationPost
     */
    readonly location: Location
}

/**
 * Request parameters for loginPost operation in DefaultApi.
 * @export
 * @interface DefaultApiLoginPostRequest
 */
export interface DefaultApiLoginPostRequest {
    /**
     * 
     * @type {LoginRequest}
     * @memberof DefaultApiLoginPost
     */
    readonly loginRequest: LoginRequest
}

/**
 * Request parameters for signupPost operation in DefaultApi.
 * @export
 * @interface DefaultApiSignupPostRequest
 */
export interface DefaultApiSignupPostRequest {
    /**
     * 
     * @type {SignupRequest}
     * @memberof DefaultApiSignupPost
     */
    readonly signupRequest: SignupRequest
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Check if the user is authenticated and receive user info in that case
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authCheckGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authCheckGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Send a friend request
     * @param {DefaultApiFriendRequestCreatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public friendRequestCreatePost(requestParameters: DefaultApiFriendRequestCreatePostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).friendRequestCreatePost(requestParameters.friendRequestCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Accept a pending friend request
     * @param {DefaultApiFriendRequestIdAcceptPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public friendRequestIdAcceptPost(requestParameters: DefaultApiFriendRequestIdAcceptPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).friendRequestIdAcceptPost(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cancel a pending friend request
     * @param {DefaultApiFriendRequestIdCancelPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public friendRequestIdCancelPost(requestParameters: DefaultApiFriendRequestIdCancelPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).friendRequestIdCancelPost(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reject a pending friend request
     * @param {DefaultApiFriendRequestIdRejectPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public friendRequestIdRejectPost(requestParameters: DefaultApiFriendRequestIdRejectPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).friendRequestIdRejectPost(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get frend requests for the authenticated user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public friendRequestsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).friendRequestsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a friend connection
     * @param {DefaultApiFriendsFriendUsernameDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public friendsFriendUsernameDelete(requestParameters: DefaultApiFriendsFriendUsernameDeleteRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).friendsFriendUsernameDelete(requestParameters.friendUsername, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List usernames of confirmed friends
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public friendsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).friendsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Report current position and retrieve recent friend locations
     * @param {DefaultApiLocationPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public locationPost(requestParameters: DefaultApiLocationPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).locationPost(requestParameters.location, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Authenticate a user and receive a session cookie
     * @param {DefaultApiLoginPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public loginPost(requestParameters: DefaultApiLoginPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).loginPost(requestParameters.loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout the authenticated user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public logoutPost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).logoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new user account
     * @param {DefaultApiSignupPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public signupPost(requestParameters: DefaultApiSignupPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).signupPost(requestParameters.signupRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



