// additional api endpoints that can't be autogenerated by the OpenAPI generator

import * as auto from "./autogen";
import axios from "axios";
export * from "./autogen";

export interface UploadMedia {
  files: FileList;
}

export interface UploadAvatar {
  file: File;
}

// FIXME: insecure
axios.defaults.withCredentials = true;

export const Api = (() => {
  const basePath = import.meta.env.VITE_API_URL;
  const configuration = new auto.Configuration({
    basePath,
  });

  return {
    ...auto.DefaultApiFactory(configuration, basePath),
    // custom helper: delete a friend by username (DELETE /friends/{friend_username})
    friendsDelete(requestParameters: { friendUsername: string }) {
      const url = `${basePath}/friends/${encodeURIComponent(
        requestParameters.friendUsername,
      )}`;
      return axios.delete(url, { withCredentials: true });
    },
  };
})();
