// additional api endpoints that can't be autogenerated by the OpenAPI generator

import * as auto from "./autogen";
export * from "./autogen";

export interface UploadMedia {
  files: FileList;
}

export interface UploadAvatar {
  file: File;
}

export const Api = (() => {
  const basePath = import.meta.env.VITE_API_URL;
  const configuration = new auto.Configuration({
    basePath,
  });

  return {
    ...auto.DefaultApiFactory(configuration, basePath),
  };
})();
